abbr -a -p command -- c 'clear -x' 
abbr -a -p command -- up 'doas dnf up -y' 
abbr -a -p command -- sus 'systemctl suspend' 
abbr -a -p command -- reboot 'systemctl reboot'
abbr -a -p command -- spot 'systemctl --user start spotifyd' 
abbr -a -p command -- kspot 'systemctl --user stop spotifyd' 
abbr -a -p command -- sspot 'systemctl --user status spotifyd'
abbr -a -p command -- als autols-toggle
abbr -a -p command -- h 'cd ~'
abbr -a -p command -- - 'cd -'
abbr -a -p command -- config 'git --git-dir=$HOME/.cfg --work-tree=$HOME'
abbr -a -p command -- lg 'lazygit'
abbr -a -p command -- lgconf 'lazygit --git-dir=$HOME/.cfg --work-tree=$HOME'
abbr -a -p command -- .. 'cd ./..'
abbr -a -p command -- ... 'cd ./../..'
abbr -a -p command -- .... 'cd ./../../..'
abbr -a -p command -- ..... 'cd ./../../../..'
abbr -a -p command -- qq 'exit'
