format = """
[ ](#ffce31)\
$os\
[ ](fg:#ffce31 bg:#ff8531)\
$username\
$hostname\
$jobs\
[ ](fg:#ff8531 bg:#ff4031)\
$directory\
[ ](fg:#ff4031 bg:none)\
$fill\
[ ](fg:#00567e bg:none)\
$git_branch\
$git_status\
$git_metrics\
$time\
$cmd_duration\
[ ](fg:#00567e)\
$line_break\
$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

[fill]
symbol = ' '
style = 'bg:none'

[cmd_duration]
min_time = 50
format = '[   $duration](bg:#00567e fg:#ffffff)'


[character]
format = '$symbol'
success_symbol = '[  ](#ff8531)'
error_symbol = '[ ✗](red) '
vimcmd_visual_symbol = '[  ](purple)'
vimcmd_symbol = '[  ](#ff8531)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#ff8531 fg:bold #000000"
format = '[$user ]($style)'
disabled = false

[os]
format = "[$symbol ]($style)"
style = "bg:#ffce31 fg:#000000"
disabled = false

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
CentOS = " "
Debian = "󰣚 "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
SUSE = " "
Ubuntu = " "
Windows = "󰨡 "

[directory]
style = "fg:bold #000000 bg:#ff4031"
format = "[$path]($style)"
truncation_length = -1
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "  "
"~" = "󰋜 "
".config" = " . "
"git" = " "
".git" = ". "
"nvim" = "  "
"vim" = "  "
"lua" = " 󰢱 "
"tmux" = "  "
"fish" = " 󰈺 "

[git_branch]
symbol = ""
style = "bg:#00567e fg:#ffffff"
format = '[ $symbol $branch]($style)'
only_attached = true

[git_status]
style = "bg:#00567e fg:#ffffff"
format = '[ $all_status$ahead_behind ]($style)'

[git_metrics]
added_style = "bg:#00567e fg:bold green"
deleted_style = "bg:#00567e fg:bold red"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[time]
disabled = false
time_format = "%H:%M" # Hour:Minute Format
style = "bg:#00567e fg:#ffffff"
format = '[   $time]($style)'

[hostname]
ssh_only = true
format = '[ @ $hostname ](bg:#ff8531 fg:#000000)'
disabled = false

[jobs]
symbol = '󱃸'
format = '[$symbol $number ](bg:#ff8531 fg:#000000)'
number_threshold = 1
symbol_threshold = 1

