# ~/.config/starship.toml

# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """[ ](#ff8531)\
$username\
$hostname\
$jobs\
[ ](fg:#ff8531 bg:#ff4031)\
$directory\
[ ](fg:#ff4031 bg:#00567e)\
$git_branch\
$git_status\
$git_metrics\
$cmd_duration\
$os\
[ ](fg:#00567e)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[fill]
symbol = ' '
style = 'bg:none'

[cmd_duration]
min_time = 50
show_milliseconds = true
format = '[   $duration](bg:#00567e fg:bold #000000)'


[character]
format = '$symbol'
success_symbol = '[  ](red)'
error_symbol = '[  ](red) '
vimcmd_visual_symbol = '[  ](purple)'
vimcmd_replace_one_symbol = '[  ](blue)'
vimcmd_replace_symbol = '[  ](blue)'
vimcmd_symbol = '[  ](cyan)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#ff8531 fg:bold #000000"
format = '[$user ]($style)'
disabled = false

[os]
format = "[ $symbol]($style)"
style = "bg:#00567e fg:0000000"
disabled = false

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
CentOS = " "
Debian = "󰣚 "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
SUSE = " "
Ubuntu = " "
Windows = "󰨡 "

[directory]
style = "fg:bold #000000 bg:#ff4031"
format = "[ $path ]($style)"
truncation_length = -1
truncation_symbol = "…/"
truncate_to_repo = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "  "
"~" = "󰋜 "
".config" = " . "
"git" = " "
".git" = ". "
"nvim" = "  "
"vim" = "  "
"lua" = " 󰢱 "
"tmux" = "  "
"fish" = " 󰈺 "

[git_branch]
symbol = ""
style = "bg:#00567e fg:bold #000000"
format = '[ $symbol $branch]($style)'
only_attached = true

[git_status]
style = "bg:#00567e fg:bold #000000"
format = '[$all_status$ahead_behind]($style)'

[git_metrics]
added_style = "bg:#00567e fg:bold green"
deleted_style = "bg:#00567e fg:bold red"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[hostname]
ssh_only = true
format = '[ @ $hostname ](bg:#ff8531 fg:#000000)'
disabled = false

[jobs]
symbol = '󱃸'
format = '[$symbol $number ](bg:#ff8531 fg:bold #000000)'
number_threshold = 1
symbol_threshold = 1
