-- Keymaps are automatically loaded on the VeryLazy event
-- vim.keymap.set("n", "qq", ":wq<CR>")
-- vim.keymap.set("n", "fq", ":q!<CR>")
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
